version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme

  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

